apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mgoi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0037-tenant/tkrw-pr712-0075-0037-app/devfile-sample-mgoi@sha256:ddb76129c95c36ebed64acc6de4071d6ddfc53be6c44ecc3bfe7a2ce48c74d68
        name: my-nodejs
        resources: {}
status: {}
