apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-mgoi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-mgoi
    app.kubernetes.io/part-of: tkrw-pr712-0075-0037-app
  name: devfile-sample-mgoi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-mgoi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-mgoi
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0037-tenant/tkrw-pr712-0075-0037-app/devfile-sample-mgoi@sha256:ddb76129c95c36ebed64acc6de4071d6ddfc53be6c44ecc3bfe7a2ce48c74d68
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
